fileUrl<-"https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06hid.csv"
download.file(fileUrl,destfile="properties.csv")
properties<-read.table("properties.csv",sep=",",header=TRUE)
head(properties)
library(dplyr)
properties$VAL
values<-properties$VAL
values<-values[!is.na(values)]
values<-values[values>=24]
properties$FES

fileUrl<-"https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FDATA.gov_NGAP.xlsx"
install.packages("xlsx")
install.packages("rJava")
download.file(fileUrl,destfile="gas.xlsx")
library(xlsx)
gas<-read.xlsx("gas.xlsx",sheetIndex=1,header=TRUE)
colIdx<-7:15
rowIdx<-18:23
dat<-read.xlsx("gas.xlsx",sheetIndex=1,colIndex=colIdx,rowIndex=rowIdx)
sum(dat$Zip*dat$Ext,na.rm=T)

fileUrl<-"https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Frestaurants.xml"
download.file(fileUrl,destfile="restaurant.xml")
install.packages("XML")
library(XML)
doc<-xmlInternalTreeParse("data.xml")
rootNode<-xmlRoot(doc)
xmlName(rootNode)
rootNode[[1]][[1]]
xmlSApply(rootNode,xmlValue)
zip<-xpathSApply(rootNode,"//zipcode",xmlValue)
count<-zip[zip==21231]


fileUrl<-"https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06pid.csv"
download.file(fileUrl,destfile="housing.csv")
install.packages("data.table")
library(data.table)
DT<-fread("housing.csv")
system.time(rowMeans(DT)[DT$SEX==1])
system.time(rowMeans(DT)[DT$SEX==2])
system.time(mean(DT[DT$SEX==1,]$pwgtp15))
system.time(mean(DT[DT$SEX==2,]$pwgtp15))
system.time(mean(DT$pwgtp15,by=DT$SEX))
system.time(replicate(1000,mean(DT$pwgtp15,by=DT$SEX)))
system.time(replicate(1000,tapply(DT$pwgtp15,DT$SEX,mean)))
system.time(replicate(1000,DT[,mean(pwgtp15),by=SEX]))
system.time(replicate(1000,sapply(split(DT$pwgtp15,DT$SEX),mean)))
mean(DT$pwgtp15,by=DT$SEX)
tapply(DT$pwgtp15,DT$SEX,mean)
DT[,mean(pwgtp15),by=SEX]
sapply(split(DT$pwgtp15,DT$SEX),mean)
