connection <- url("http://biostat.jhsph.edu/~jleek/contact.html")
html <- readLines(connection)
nchar("abcdef")
nchar(html[10])
nchar(html[20])
nchar(html[30])
nchar(html[100])

install.packages("foreign")
library("foreign")
ff <- c(-5,4,4)
data <- read.fwf("getdata_wksst8110.for",widths = c(-1,9,ff,ff,ff,ff),skip=4)
ff <- c("5X","A4","A4")
data <- read.fortran("getdata_wksst8110.for", c("1X","A9",ff,ff,ff,ff))
sum(data[4])
